version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "1234:1234"
        volumes:
            - $PWD/nginx/web:/usr/share/nginx/html
            - $PWD/nginx/vhost:/etc/nginx/conf.d
            - $PWD/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php
            - mysql
        networks:
            - lan

    php:
        build: ./php-fpm
        ports:
            - "9002:9000"
        volumes:
            - $PWD/nginx/web:/usr/share/nginx/html
        networks:
            - lan

    mysql:
        build: ./mysql
        ports:
            - "9003:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - $PWD/mysql/conf:/etc/mysql/conf.d
            - $PWD/mysql/data:/var/lib/mysql
        networks:
            - lan

    redis:
        build: ./redis
        ports:
            - "6380:6379"
        volumes:
            - "./redis/data:/data"
        command: --appendonly yes
        environment:
            - REDIS_PASSWORD=test
        networks:
            - lan

networks:
    lan:
        driver: bridge

